import os
from os.path import join


configfile: "config/config.yaml"
report: "workflow.rst"

rawdir = join(config["datadir"]) # the directory with data to be processed
outdir = join(config["datadir"], "derivatives") # the directory where derivatives are to be stored

environmentdir = join(config["rootdir"], "envs")
resourcedir = join(config["rootdir"], "resources")
workflowdir = join(config["rootdir"], "workflow")


# Create the results directory if it doesn't exist already
os.makedirs(outdir, exist_ok=True)

# Specifies the files which should exist at the end of the processing
endfiles = [
    # In this case, it is the average time series for each of the ROIs, and the FC matrix
    os.path.join(
            outdir,
            "xcp_d",
            "sub-{subid}",
            "ses-1",
            "func",
            "sub-{subid}_ses-1_task-rest_dir-AP_space-fsLR_seg-Glasser_den-91k_stat-mean_timeseries.ptseries.nii"
        ),
        os.path.join(
            outdir,
            "xcp_d",
            "sub-{subid}",
            "ses-1",
            "func",
            "sub-{subid}_ses-1_task-rest_dir-PA_space-fsLR_seg-Glasser_den-91k_stat-mean_timeseries.ptseries.nii"
        ),
        os.path.join(
            outdir,
            "xcp_d",
            "sub-{subid}",
            "ses-1",
            "func",
            "sub-{subid}_ses-1_task-rest_dir-AP_space-fsLR_seg-Glasser_den-91k_stat-pearsoncorrelation_boldmap.pconn.nii"
        ),
        os.path.join(
            outdir,
            "xcp_d",
            "sub-{subid}",
            "ses-1",
            "func",
            "sub-{subid}_ses-1_task-rest_dir-PA_space-fsLR_seg-Glasser_den-91k_stat-pearsoncorrelation_boldmap.pconn.nii"
        ),
        os.path.join(
            outdir,
            "xcp_d",
            "sub-{subid}",
            "ses-2",
            "func",
            "sub-{subid}_ses-2_task-rest_dir-AP_space-fsLR_seg-Glasser_den-91k_stat-mean_timeseries.ptseries.nii"
        ),
        os.path.join(
            outdir,
            "xcp_d",
            "sub-{subid}",
            "ses-2",
            "func",
            "sub-{subid}_ses-2_task-rest_dir-PA_space-fsLR_seg-Glasser_den-91k_stat-mean_timeseries.ptseries.nii"
        ),
        os.path.join(
            outdir,
            "xcp_d",
            "sub-{subid}",
            "ses-2",
            "func",
            "sub-{subid}_ses-2_task-rest_dir-AP_space-fsLR_seg-Glasser_den-91k_stat-pearsoncorrelation_boldmap.pconn.nii"
        ),
        os.path.join(
            outdir,
            "xcp_d",
            "sub-{subid}",
            "ses-2",
            "func",
            "sub-{subid}_ses-2_task-rest_dir-PA_space-fsLR_seg-Glasser_den-91k_stat-pearsoncorrelation_boldmap.pconn.nii"
        )   
]

# Define the subject IDs to be processed
# subids = ["1002", "1003", "1004", "1005", "1006", "1009", "1010", "1012"]
# E.g. this should select all the subject IDs present in your BIDS directory
# subids = [i[4:] for i in os.listdir(rawdir) if i.startswith('sub-')]
subids = [fname[:4] for fname in os.listdir(os.path.join(rawdir, "imagingcollection01")) if os.path.exists(os.path.join(rawdir, "imagingcollection01", fname, "unprocessed", "T1w_MPR", f"{fname}_T1w_MPR.nii.gz"))]


rule all:
    """
    Generates all required outputs
    """
    input:
        expand(endfiles, subid=subids)

# Transform an HCP dataset into a BIDS format
rule bidsify:
    input:
        os.path.join(rawdir, "imagingcollection01", "{subid}_01_MR", "unprocessed", "T1w_MPR", "{subid}_01_MR_T1w_MPR.nii.gz")
    params:
        workflow_dir = workflowdir,
        data_dir = rawdir,
        subid = "{subid}",
        resource_dir = resourcedir
    output:
        os.path.join(rawdir, "BIDS", "sub-{subid}", "ses-1", "anat", "sub-{subid}_ses-1_T1w.nii.gz"),
        os.path.join(rawdir, "BIDS", "sub-{subid}", "ses-1", "anat", "sub-{subid}_ses-1_T2w.nii.gz"),
        os.path.join(rawdir, "BIDS", "sub-{subid}", "ses-1", "fmap", "sub-{subid}_ses-1_task-rest_dir-AP_epi.nii.gz"),
        os.path.join(rawdir, "BIDS", "sub-{subid}", "ses-1", "fmap", "sub-{subid}_ses-1_task-rest_dir-PA_epi.nii.gz"),
        os.path.join(rawdir, "BIDS", "sub-{subid}", "ses-2", "fmap", "sub-{subid}_ses-2_task-rest_dir-AP_epi.nii.gz"),
        os.path.join(rawdir, "BIDS", "sub-{subid}", "ses-2", "fmap", "sub-{subid}_ses-2_task-rest_dir-PA_epi.nii.gz"),
        os.path.join(rawdir, "BIDS", "sub-{subid}", "ses-1", "func", "sub-{subid}_ses-1_task-rest_dir-AP_bold.nii.gz"),
        os.path.join(rawdir, "BIDS", "sub-{subid}", "ses-1", "func", "sub-{subid}_ses-1_task-rest_dir-PA_bold.nii.gz"),
        os.path.join(rawdir, "BIDS", "sub-{subid}", "ses-2", "func", "sub-{subid}_ses-2_task-rest_dir-AP_bold.nii.gz"),
        os.path.join(rawdir, "BIDS", "sub-{subid}", "ses-2", "func", "sub-{subid}_ses-2_task-rest_dir-PA_bold.nii.gz"),
    shell:
        "python {params.workflow_dir}/bidsifyhcp/main.py --hcp_dir {params.data_dir}/imagingcollection01 --target_dir {params.data_dir}/BIDS --subid {params.subid} && "
        "python {params.workflow_dir}/fmap_insert_intended_for.py --target_dir {params.data_dir}/BIDS --subid {params.subid} && "
        "cp {params.resource_dir}/dataset_description.json {params.data_dir}/BIDS/dataset_description.json"

# Apply fMRIPrep preprocessing pipeline to the data
# https://fmriprep.org/en/stable/
rule fmriprep:
    input:
        os.path.join(rawdir, "BIDS", "sub-{subid}", "ses-1", "anat", "sub-{subid}_ses-1_T1w.nii.gz"),
        os.path.join(rawdir, "BIDS", "sub-{subid}", "ses-1", "anat", "sub-{subid}_ses-1_T2w.nii.gz"),
        os.path.join(rawdir, "BIDS", "sub-{subid}", "ses-1", "fmap", "sub-{subid}_ses-1_task-rest_dir-AP_epi.nii.gz"),
        os.path.join(rawdir, "BIDS", "sub-{subid}", "ses-1", "fmap", "sub-{subid}_ses-1_task-rest_dir-PA_epi.nii.gz"),
        os.path.join(rawdir, "BIDS", "sub-{subid}", "ses-2", "fmap", "sub-{subid}_ses-2_task-rest_dir-AP_epi.nii.gz"),
        os.path.join(rawdir, "BIDS", "sub-{subid}", "ses-2", "fmap", "sub-{subid}_ses-2_task-rest_dir-PA_epi.nii.gz"),
        os.path.join(rawdir, "BIDS", "sub-{subid}", "ses-1", "func", "sub-{subid}_ses-1_task-rest_dir-AP_bold.nii.gz"),
        os.path.join(rawdir, "BIDS", "sub-{subid}", "ses-1", "func", "sub-{subid}_ses-1_task-rest_dir-PA_bold.nii.gz"),
        os.path.join(rawdir, "BIDS", "sub-{subid}", "ses-2", "func", "sub-{subid}_ses-2_task-rest_dir-AP_bold.nii.gz"),
        os.path.join(rawdir, "BIDS", "sub-{subid}", "ses-2", "func", "sub-{subid}_ses-2_task-rest_dir-PA_bold.nii.gz"),
    params:
        bids_dir=os.path.join(rawdir, "BIDS"),
        out_dir=outdir,
        fs_license_dir=resourcedir,
        workflow_dir=workflowdir
        # root_dir=rootdir
    threads: 8
    resources:
        mem='64G',
        mem_mib='64000',
        disk_mb='64000',
        disk_mib='64000',
        mem_per_thread='64G',
        time='5-00:00:00'
    output:
        os.path.join(
            outdir,
            "fmriprep",
            "sub-{subid}",
            "ses-1",
            "func",
            "sub-{subid}_ses-1_task-rest_dir-AP_space-fsLR_den-91k_bold.dtseries.nii"
        ),
        os.path.join(
            outdir,
            "fmriprep",
            "sub-{subid}",
            "ses-1",
            "func",
            "sub-{subid}_ses-1_task-rest_dir-PA_space-fsLR_den-91k_bold.dtseries.nii"
        ),
        os.path.join(
            outdir,
            "fmriprep",
            "sub-{subid}",
            "ses-2",
            "func",
            "sub-{subid}_ses-2_task-rest_dir-AP_space-fsLR_den-91k_bold.dtseries.nii"
        ),
        os.path.join(
            outdir,
            "fmriprep",
            "sub-{subid}",
            "ses-2",
            "func",
            "sub-{subid}_ses-2_task-rest_dir-PA_space-fsLR_den-91k_bold.dtseries.nii"
        )
    container:
        config["containers"]["fmriprep"]
    shell:
        "rm -rf {params.out_dir}/freesurfer/sub-{wildcards.subid} && "
        "fmriprep "
        "{params.bids_dir} {params.out_dir}/fmriprep participant "
        "--fs-license-file {params.fs_license_dir}/license.txt "
        "--work-dir {params.out_dir}/temp "
        # "--skip-bids-validation "
        "--participant_label {wildcards.subid} "
        # "--session-label 1 2 "
        # "--clean-workdir "
        "--output-spaces MNI152NLin2009cAsym:res-2 fsLR "
        "--cifti-output "
        "--skip-bids-validation "
        "--nthreads 16 "
        "--omp-nthreads 16 && "
        "cp -R {params.out_dir}/fmriprep/sub-{wildcards.subid}/ses-1/anat {params.out_dir}/fmriprep/sub-{wildcards.subid}/ses-2/anat && "
        "python {params.workflow_dir}/rename_anat_files.py --anat_dir {params.out_dir}/fmriprep/sub-{wildcards.subid}/ses-2/anat && "
        "rm -rf {params.out_dir}/temp"



# Apply XCP-D to the fMRIPrep processed data using the Desikan-Killiany atlas we created from FreeSurfer parcellation
# To change the preprocessing parameters, such as the smoothing kernel width, confounds to be used for denoising, etc.
# you can change the command line arguments to XCP-D in the shell command bellow. The usage instructions can be found here:
# https://xcp-d.readthedocs.io/en/latest/usage.html#command-line-arguments
rule xcp_d:
    input:
        os.path.join(
            outdir,
            "fmriprep",
            "sub-{subid}",
            "ses-1",
            "func",
            "sub-{subid}_ses-1_task-rest_dir-AP_space-fsLR_den-91k_bold.dtseries.nii"
        ),
        os.path.join(
            outdir,
            "fmriprep",
            "sub-{subid}",
            "ses-1",
            "func",
            "sub-{subid}_ses-1_task-rest_dir-PA_space-fsLR_den-91k_bold.dtseries.nii"
        ),
        os.path.join(
            outdir,
            "fmriprep",
            "sub-{subid}",
            "ses-2",
            "func",
            "sub-{subid}_ses-2_task-rest_dir-AP_space-fsLR_den-91k_bold.dtseries.nii"
        ),
        os.path.join(
            outdir,
            "fmriprep",
            "sub-{subid}",
            "ses-2",
            "func",
            "sub-{subid}_ses-2_task-rest_dir-PA_space-fsLR_den-91k_bold.dtseries.nii"
        )
    params:
        out_dir=outdir,
        fs_license_dir=resourcedir,
        workflow_dir=workflowdir
    threads: 8
    resources:
        mem='32G',
        time='1-00:00:00'
    output:
        os.path.join(
            outdir,
            "xcp_d",
            "sub-{subid}",
            "ses-1",
            "func",
            "sub-{subid}_ses-1_task-rest_dir-AP_space-fsLR_seg-Glasser_den-91k_stat-mean_timeseries.ptseries.nii"
        ),
        os.path.join(
            outdir,
            "xcp_d",
            "sub-{subid}",
            "ses-1",
            "func",
            "sub-{subid}_ses-1_task-rest_dir-PA_space-fsLR_seg-Glasser_den-91k_stat-mean_timeseries.ptseries.nii"
        ),
        os.path.join(
            outdir,
            "xcp_d",
            "sub-{subid}",
            "ses-1",
            "func",
            "sub-{subid}_ses-1_task-rest_dir-AP_space-fsLR_seg-Glasser_den-91k_stat-pearsoncorrelation_boldmap.pconn.nii"
        ),
        os.path.join(
            outdir,
            "xcp_d",
            "sub-{subid}",
            "ses-1",
            "func",
            "sub-{subid}_ses-1_task-rest_dir-PA_space-fsLR_seg-Glasser_den-91k_stat-pearsoncorrelation_boldmap.pconn.nii"
        ),
        os.path.join(
            outdir,
            "xcp_d",
            "sub-{subid}",
            "ses-2",
            "func",
            "sub-{subid}_ses-2_task-rest_dir-AP_space-fsLR_seg-Glasser_den-91k_stat-mean_timeseries.ptseries.nii"
        ),
        os.path.join(
            outdir,
            "xcp_d",
            "sub-{subid}",
            "ses-2",
            "func",
            "sub-{subid}_ses-2_task-rest_dir-PA_space-fsLR_seg-Glasser_den-91k_stat-mean_timeseries.ptseries.nii"
        ),
        os.path.join(
            outdir,
            "xcp_d",
            "sub-{subid}",
            "ses-2",
            "func",
            "sub-{subid}_ses-2_task-rest_dir-AP_space-fsLR_seg-Glasser_den-91k_stat-pearsoncorrelation_boldmap.pconn.nii"
        ),
        os.path.join(
            outdir,
            "xcp_d",
            "sub-{subid}",
            "ses-2",
            "func",
            "sub-{subid}_ses-2_task-rest_dir-PA_space-fsLR_seg-Glasser_den-91k_stat-pearsoncorrelation_boldmap.pconn.nii"
        )
    container:
        config["containers"]["xcp_d"]
    shell:
        "rm -rf {params.workflow_dir}/working_dir && "
        "xcp_d "
        "{params.out_dir}/fmriprep "
        "{params.out_dir}/xcp_d "
        "participant "
        "--participant-label {wildcards.subid} "
        "--session-id 1 2 "
        "--mode linc "
        "--despike "
        "--nuisance-regressors acompcor "
        "--atlases Glasser "
        "--head_radius 40 "
        "--fs-license-file {params.fs_license_dir}/license.txt "
        "--smoothing 6 "
        "--n_cpus 16"