import os
from os.path import join


configfile: "config/config.yaml"
report: "workflow.rst"

rawdir = join(config["datadir"]) # the directory with data to be processed
outdir = join(config["datadir"], "derivatives") # the directory where derivatives are to be stored

environmentdir = join(config["rootdir"], "envs")
resourcedir = join(config["rootdir"], "resources")
workflowdir = join(config["rootdir"], "workflow")


# Create the results directory if it doesn't exist already
os.makedirs(outdir, exist_ok=True)

# Specifies the files which should exist at the end of the processing
endfiles = [
    # In this case, it is the average time series for each of the ROIs, and the FC matrix
    # os.path.join(
    #     outdir,
    #     "xcp_d",
    #     "sub-{subid}",
    #     "func",
    #     "sub-{subid}_task-rest_space-fsLR_seg-Glasser_den-91k_stat-mean_timeseries.ptseries.nii"
    # ),
    # os.path.join(
    #     outdir,
    #     "xcp_d",
    #     "sub-{subid}",
    #     "func",
    #     "sub-{subid}_task-rest_space-fsLR_seg-Glasser_den-91k_stat-pearsoncorrelation_boldmap.pconn.nii"
    # )
    os.path.join(rawdir, "BIDS", "dataset_description.json")
]

# Define the subject IDs to be processed
subids = ["LEGK010"]
# E.g. this should select all the subject IDs present in your BIDS directory
# subids = [i[4:] for i in os.listdir(rawdir) if i.startswith('sub-')]


rule all:
    """
    Generates all required outputs
    """
    input:
        expand(endfiles, subid=subids)

rule bidsify:
    input:
        os.path.join(rawdir, "HCP")
    params:
        workflow_dir = workflowdir
    output:
        os.path.join(rawdir, "BIDS", "dataset_description.json")
    shell:
        "python {params.workflow_dir}/bidsifyhcp/main.py --hcp_dir {input} --target_dir {output} && "
        "touch {output}"

# Apply fMRIPrep preprocessing pipeline to the data
# https://fmriprep.org/en/stable/
rule fmriprep:
    input:
        os.path.join(rawdir, "sub-{subid}", "anat", "sub-{subid}_T1w.nii.gz"),
        os.path.join(rawdir, "sub-{subid}", "anat", "sub-{subid}_T2w.nii.gz"), # comment out if your data does not contain T2
        os.path.join(rawdir, "sub-{subid}", "fmap", "sub-{subid}_magnitude1.nii.gz"),
        os.path.join(rawdir, "sub-{subid}", "fmap", "sub-{subid}_magnitude2.nii.gz"),
        os.path.join(rawdir, "sub-{subid}", "fmap", "sub-{subid}_phasediff.nii.gz"),
        os.path.join(
            rawdir,
            "sub-{subid}",
            "func",
            "sub-{subid}_task-rest_bold.nii.gz"
        )
    params:
        bids_dir=rawdir,
        out_dir=outdir,
        fs_license_dir=resourcedir
    threads: 8
    resources:
        mem='16G',
        time='12:00:00'
    output:
        os.path.join(
            outdir,
            "fmriprep",
            "sub-{subid}",
            "func",
            "sub-{subid}_task-rest_space-fsLR_den-91k_bold.dtseries.nii"
        )
    container:
        config["containers"]["fmriprep"]
    shell:
        "rm -rf {params.out_dir}/freesurfer/sub-{wildcards.subid} && "
        "fmriprep "
        "{params.bids_dir} {params.out_dir}/fmriprep participant "
        "--fs-license-file {params.fs_license_dir}/license.txt "
        "--skip-bids-validation "
        "--participant_label {wildcards.subid} "
        "--output-spaces MNI152NLin2009cAsym:res-2 fsLR "
        "--cifti-output "
        "--skip-bids-validation "
        "--nthreads 16 "
        "--omp-nthreads 16"


# Apply XCP-D to the fMRIPrep processed data using the Desikan-Killiany atlas we created from FreeSurfer parcellation
# To change the preprocessing parameters, such as the smoothing kernel width, confounds to be used for denoising, etc.
# you can change the command line arguments to XCP-D in the shell command bellow. The usage instructions can be found here:
# https://xcp-d.readthedocs.io/en/latest/usage.html#command-line-arguments
rule xcp_d:
    input:
        os.path.join(
            outdir,
            "fmriprep",
            "sub-{subid}",
            "func",
            "sub-{subid}_task-rest_space-fsLR_den-91k_bold.dtseries.nii"
        )
    params:
        out_dir=outdir,
        fs_license_dir=resourcedir,
        workflow_dir=workflowdir
    threads: 8
    resources:
        mem='32G',
        time='12:00:00'
    output:
        os.path.join(
            outdir,
            "xcp_d",
            "sub-{subid}",
            "func",
            "sub-{subid}_task-rest_space-fsLR_seg-Glasser_den-91k_stat-mean_timeseries.ptseries.nii"
        ),
        os.path.join(
            outdir,
            "xcp_d",
            "sub-{subid}",
            "func",
            "sub-{subid}_task-rest_space-fsLR_seg-Glasser_den-91k_stat-pearsoncorrelation_boldmap.pconn.nii"
        )
    container:
        config["containers"]["xcp_d"]
    shell:
        "rm -rf {params.workflow_dir}/working_dir && "
        "xcp_d "
        "{params.out_dir}/fmriprep "
        "{params.out_dir}/xcp_d "
        "participant "
        "--participant-label {wildcards.subid} "
        "--mode linc "
        "--despike "
        "--nuisance-regressors acompcor "
        "--atlases Glasser "
        "--head_radius 40 "
        "--fs-license-file {params.fs_license_dir}/license.txt "
        "--smoothing 6 "
        "--n_cpus 16"